### ISSUE TITLE
API not working anymore

### ISSUE THREAD

**Issue by SeifB13** [amirreza1307/coursera-auto-answer#3]
**Describe the bug**
When I tried to use the extension, the API isn't working anymore

**To Reproduce**
1. Go to any coursera quiz
2. Click on Inspect
3. Go to console
4. Launch the extension
5. See the error on the console

**Expected behavior**
It's supposed to show the result of GPT answers and select them on the quiz

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Brave & Edge

**Comment by amirreza1307** [comment]
Yes, API is down, I will try to replace it with a new API soon
